<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>esb</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^[^#]\s*.*:(\s*\[?| &amp;.+)?$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)</string>
	<key>keyEquivalent</key>
	<string>^~@e</string>
	<key>name</key>
	<string>ESB</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#erb</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!(expectation|behaviou?r|strateg(?:y|ie))s?</string>
			<key>name</key>
			<string>keyword.header.esb</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*([\w_]+\s*\:)</string>
			<key>name</key>
			<string>variable.key.esb</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.list.esb</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([\+\-])\s*\w+</string>
			<key>name</key>
			<string>entity.list.esb</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^---+$</string>
			<key>name</key>
			<string>keyword.operator.divider.esb</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.source.esb</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>erb</key>
		<dict>
			<key>begin</key>
			<string>&lt;%+(?!&gt;)=?</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ruby</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%&gt;</string>
			<key>name</key>
			<string>source.ruby.rails.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ruby</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*?(?=%&gt;)</string>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.esb</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.esb</string>
	<key>uuid</key>
	<string>B6D3CCA0-FDC8-442A-8D41-515DD8F93C50</string>
</dict>
</plist>
